run_dir: ./output/benezerg/pendulum_state/${now:%Y-%m-%d}/${now:%H-%M-%S}_${user.wandb_suffix}

wandb_enabled: True
wandb_entity: GB-Northeastern-Projects
wandb_project: CS-7268-Group-Project
wandb_suffix: h200_train_controller_symbolic_set_2

load_lyaloss: null
Vmin_x_pgd_path: null 
derivative_x_buffer_path: null 
